### PR TITLE
Gcm json payload

### PR DESCRIPTION
**Pull request by wolfhechel**
Addresses the issue with wrong error handling when sending JSON requests.

### CODE REVIEW

**Comment by rakanalh** [comment]
This looks good. I was  thinking that we shouldn't use GCMUnavailableException name because it's misleading. Did you test this on your production environment?

**Comment by wolfhechel** [comment]
Yes this is running on our production environment and works well. I agree with you on that note, however I don't see a reason to create an Exception-type for this in pushy since it will basically be ignored in the end.

One could use GCMException for it though, but in the end there's really nothing that's made different depending on what exception we throw there.

**Comment by rakanalh** [comment]
Yes but i believe naming should be clear. Can you make the change so that i can merge this?

Many thanks for testing this on production

**Comment by wolfhechel** [comment]
Done, and done!

Sure thing, thank you for actively participating in discussions and PR's!

**Pull request merged**
